# Generated by Django 2.2.5 on 2019-10-20 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='creation_date',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='modification_date',
            new_name='fecha_modificacion',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='introduction',
            new_name='texto_introduccion',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='state',
        ),
        migrations.AddField(
            model_name='article',
            name='estado',
            field=models.CharField(choices=[['DRF', 'Borrador'], ['PUB', 'Publicado']], default='DRF', max_length=3),
        ),
        migrations.AddField(
            model_name='article',
            name='imagen',
            field=models.URLField(default='http://ella.practicalaction.org/wp-content/themes/ella/images/no-photo.png'),
        ),
        migrations.AddField(
            model_name='article',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
