# Generated by Django 2.2.5 on 2019-10-20 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_fecha_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body',
        ),
        migrations.AddField(
            model_name='article',
            name='contenido',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 20, 23, 37, 50, 712274), null=True),
        ),
    ]
