# Generated by Django 2.2.5 on 2019-10-20 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20191020_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='url',
        ),
        migrations.AlterField(
            model_name='article',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 20, 23, 42, 20, 974829), null=True),
        ),
    ]
