# Generated by Django 2.2.5 on 2019-10-22 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20191020_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 22, 18, 55, 32, 539715), null=True),
        ),
    ]
