# Generated by Django 2.2.5 on 2019-10-22 19:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20191022_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='articles.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 22, 19, 0, 38, 866699), null=True),
        ),
    ]
